image: rocker/verse:latest

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/.cache/"

before_script:
  - mkdir -p .cache
  - apt-get update && apt-get install -y --no-install-recommends libudunits2-dev libsodium-dev libssl-dev
  - Rscript -e "devtools::install_deps(dependencies=TRUE, lib = '.cache')"
  - Rscript -e "devtools::install_github(c('noamross/openxlsx', 'ropensci/cyphr'), lib = '.cache')"


cache:
  key: common-cache
  paths:
    - .cache/

build:
  only:
    - pushes
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    paths:
    - outputs/
  script:
    - ./00-get-eidith-data.R
    - ./make.R


build_w_new_data_and_upload:
  only:
    - schedules
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    paths:
    - outputs/
  script:
    - ./00-get-eidith-data.R
    - ./make.R
    - ./dropbox_upload.R
