version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
    - image: rocker/verse:latest
    steps:
    - run: apt-get update && apt-get install -y --no-install-recommends libudunits2-dev libsodium-dev libssl-dev
    - checkout
    - restore_cache:
        keys:
        - deps4-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
        - deps4-{{ .Branch }}
        - deps4
    - run:
        command: |
          Rscript -e "devtools::install_deps(dependencies=TRUE)"
          Rscript -e "devtools::install_github('noamross/openxlsx', 'ropensci/cyphr')"
    - save_cache:
        key: deps4-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
        paths:
        - /usr/local/lib/R/site-library
    - run: ./00-get-eidith-data.R
    - run: ./make.R
    - store_artifacts:
        path: /root/main/outputs/
        destination: artifacts
  build_w_new_data_and_upload:
    working_directory: ~/main
    docker:
    - image: rocker/verse:latest
    steps:
    - run:
        command: |
          apt-get update && apt-get install -y --no-install-recommends libudunits2-dev libsodium-dev libssl-dev
    - checkout
    - restore_cache:
        keys:
        - deps4-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
        - deps4-{{ .Branch }}
        - deps4
    - run:
        command: |
          Rscript -e "devtools::install_deps(dependencies=TRUE)"
          Rscript -e "devtools::install_github('noamross/openxlsx', 'ropensci/cyphr')"
    - save_cache:
        key: deps4-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
        paths:
        - /usr/local/lib/R/site-library
    - run: ./00-get-eidith-data.R
    - run: ./make.R
    - store_artifacts:
        path: /root/main/outputs/
        destination: artifacts
    - store_artifacts:
        path: /root/main/raw-eidith-data/
        destination: raw-eidith-data
    - run: ./dropbox_upload.R

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "00 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_w_new_data_and_upload
